# 动态数据源统一接口测试脚本

## 1. 查看当前所有数据源
GET http://localhost:8081/api/datasource/list
Content-Type: application/json

###

## 2. 添加新的数据源 db2
POST http://localhost:8081/api/datasource/add
Content-Type: application/x-www-form-urlencoded

dsName=db2
&url=jdbc:h2:mem:db2
&username=sa
&password=
&driverClassName=org.h2.Driver
&initialSize=5
&minIdle=5
&maxActive=20
&maxWait=60000

###

## 3. 添加新的数据源 db3
POST http://localhost:8081/api/datasource/add
Content-Type: application/x-www-form-urlencoded

dsName=db3
&url=jdbc:h2:mem:db3
&username=sa
&password=
&driverClassName=org.h2.Driver
&initialSize=5
&minIdle=5
&maxActive=20
&maxWait=60000

###

## 4. 再次查看所有数据源
GET http://localhost:8081/api/datasource/list
Content-Type: application/json

###

## 5. 为db2数据源添加Redis集群配置
POST http://localhost:8081/api/datasource/redis/add
Content-Type: application/x-www-form-urlencoded

dsName=db2
&redisHost=localhost
&redisPort=6379

###

## 6. 为db3数据源添加Redis集群配置
POST http://localhost:8081/api/datasource/redis/add
Content-Type: application/x-www-form-urlencoded

dsName=db3
&redisHost=localhost
&redisPort=6380

###

## 7. 查看所有Redis集群配置
GET http://localhost:8081/api/datasource/redis/list
Content-Type: application/json

###

## 8. 在 db2 中添加用户
POST http://localhost:8081/api/datasource/db2/users
Content-Type: application/json

{
  "name": "Tom",
  "email": "tom@example.com"
}

###

## 9. 在 db2 中查询所有用户
GET http://localhost:8081/api/datasource/db2/users
Content-Type: application/json

###

## 10. 在 db3 中添加用户
POST http://localhost:8081/api/datasource/db3/users
Content-Type: application/json

{
  "name": "Jerry",
  "email": "jerry@example.com"
}

###

## 11. 在 db3 中查询所有用户
GET http://localhost:8081/api/datasource/db3/users
Content-Type: application/json

###

## 12. 在默认数据源中添加用户
POST http://localhost:8081/api/datasource/dataSource1/users
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@example.com"
}

###

## 13. 在默认数据源中查询所有用户
GET http://localhost:8081/api/datasource/dataSource1/users
Content-Type: application/json

###

## 14. 向所有数据源添加用户
POST http://localhost:8081/api/datasource/all/users
Content-Type: application/json

{
  "name": "All DataSources User",
  "email": "all@example.com"
}

###

## 15. 从所有数据源查询用户
GET http://localhost:8081/api/datasource/all/users
Content-Type: application/json

###

## 16. 使用简化接口向所有数据源添加用户
POST http://localhost:8081/users/all
Content-Type: application/json

{
  "name": "All DS User via UserController",
  "email": "all2@example.com"
}

###

## 17. 使用简化接口从所有数据源查询用户
GET http://localhost:8081/users/all
Content-Type: application/json

###

## 18. 使用简化接口在指定数据源中添加用户
POST http://localhost:8081/users/dynamic/db2
Content-Type: application/json

{
  "name": "Simplified Tom",
  "email": "simplified.tom@example.com"
}

###

## 19. 使用简化接口从指定数据源中获取用户
GET http://localhost:8081/users/dynamic/db2
Content-Type: application/json

###

## 20. 在db2的Redis中设置键值对
POST http://localhost:8081/api/datasource/db2/redis/set?key=username&value=Tom
Content-Type: application/json

###

## 21. 从db2的Redis中获取值
GET http://localhost:8081/api/datasource/db2/redis/get?key=username
Content-Type: application/json

###

## 22. 删除db3数据源的Redis集群配置
DELETE http://localhost:8081/api/datasource/redis/remove?dsName=db3
Content-Type: application/json

###

## 23. 再次查看所有Redis集群配置
GET http://localhost:8081/api/datasource/redis/list
Content-Type: application/json

###

## 24. 删除数据源 db3
DELETE http://localhost:8081/api/datasource/remove?dsName=db3
Content-Type: application/json

###

## 25. 再次查看所有数据源，确认 db3 已被删除
GET http://localhost:8081/api/datasource/list
Content-Type: application/json