# 动态数据源统一接口测试脚本

## 1. 查看当前所有数据源
GET http://localhost:8080/api/datasource/list
Content-Type: application/json

###

## 2. 添加新的数据源 db2
POST http://localhost:8080/api/datasource/add
Content-Type: application/x-www-form-urlencoded

dsName=db2
&url=jdbc:h2:mem:db2
&username=sa
&password=
&driverClassName=org.h2.Driver
&initialSize=5
&minIdle=5
&maxActive=20
&maxWait=60000

###

## 3. 添加新的数据源 db3
POST http://localhost:8080/api/datasource/add
Content-Type: application/x-www-form-urlencoded

dsName=db3
&url=jdbc:h2:mem:db3
&username=sa
&password=
&driverClassName=org.h2.Driver
&initialSize=5
&minIdle=5
&maxActive=20
&maxWait=60000

###

## 4. 添加新的数据源 db4
POST http://localhost:8080/api/datasource/add
Content-Type: application/x-www-form-urlencoded

dsName=db4
&url=jdbc:h2:mem:db4
&username=sa
&password=
&driverClassName=org.h2.Driver
&initialSize=5
&minIdle=5
&maxActive=20
&maxWait=60000

###

## 5. 再次查看所有数据源
GET http://localhost:8080/api/datasource/list
Content-Type: application/json

###

## 6. 在 db2 中添加用户
POST http://localhost:8080/api/datasource/db2/users
Content-Type: application/json

{
  "name": "Tom",
  "email": "tom@example.com"
}

###

## 7. 在 db2 中查询所有用户
GET http://localhost:8080/api/datasource/db2/users
Content-Type: application/json

###

## 8. 在 db3 中添加用户
POST http://localhost:8080/api/datasource/db3/users
Content-Type: application/json

{
  "name": "Jerry",
  "email": "jerry@example.com"
}

###

## 9. 在 db3 中查询所有用户
GET http://localhost:8080/api/datasource/db3/users
Content-Type: application/json

###

## 10. 删除数据源 db4
DELETE http://localhost:8080/api/datasource/remove?dsName=db4
Content-Type: application/json

###

## 11. 再次查看所有数据源，确认 db4 已被删除
GET http://localhost:8080/api/datasource/list
Content-Type: application/json

###

## 12. 使用简化接口在数据源db2中添加用户
POST http://localhost:8080/users/dynamic/db2
Content-Type: application/json

{
  "name": "Simplified Tom",
  "email": "simplified.tom@example.com"
}

###

## 13. 使用简化接口从数据源db2中获取用户
GET http://localhost:8080/users/dynamic/db2
Content-Type: application/json